spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ${GITHUB_CLIENT_ID}
            clientSecret: ${GITHUB_CLIENT_SECRET}
  logging:
    level:
      org:
        springframework:
          security: DEBUG
  datasource:
    url: "jdbc:h2:mem:test"
    driverClassName: org.h2.Driver
    username: sa
    password: ""

  jpa:
    show-sql: True
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: false
      path: /h2
