name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Instala Java 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Verificar build
        run: mvn --batch-mode --update-snapshots verify 

      - name: Pruebas unitarias
        run: mvn test
